### ISSUE TITLE
Installation Documentation Leads To Errors

### ISSUE THREAD

**Issue by Elshara** [wildstar84/fauxdacious#10]
Hello,
I am a new user to fauxdacious.
I came across your project via a back redirect while Google searching some troubleshooting steps that Audacious was unable to fix.
Things like streams buffering for mp3 and AAC audio.
Its being unable to support https or flac streams due to keys not being generated and a lack of metadata support respectively.
Quite literally a search for '.lrc crashing Audacious' in Google led me to your project's FAQ.
In case you come across any other people saying they can't build Audacious, I have narrowed down the issue to a poorly built installation tutorial.
As I am a fairly advanced Linux user myself, I have rewritten it so that it is compatible with copy paste in terminal.
Some areas of it (see below) I am still figuring out. Though I figured I'd help you out in progressing this project further as to me it is the best damn player Linux will ever see.
As a side note, I should let you know that a friend of mine, who tried to install this on Windows, reported that it is inaccessible to screen reading users. Due to a programming language issue that regular Audacious code samples are still in the process of fixing.
Here's what I've been able to decode into a workable basic documentation based on my understanding. Feel free to correct/update

(New: Basic Intro)
Here is a simpler, updated, modern way to install the best fork of Audacious media player. Transforming your premium audio experience into a pro video media center.
(To see the original documentation, click here.)
https://github.com/wildstar84/fauxdacious
(added)
Steps:
1. Dependency check. To install all dependencies at once, you need to be running as the Root user or be a local system administrator. Assuming you are on Ubuntu 22.04 or newer. Copy and paste the following line into a terminal. This gets the dependencies for both classic Audacious plus Fauxdacious. Useful when building either program from its own source code.
(the original had syntax errors and dependencies in separate sections)
sudo apt-get install automake build-essential git libadplug-dev libasound2-dev libavformat-dev libbinio-dev libbs2b-dev libcddb2-dev libcdio-cdda-dev libcue-dev libcurl4-gnutls-dev libdbus-glib-1-dev libfaad-dev libflac-dev libfluidsynth-dev libgl1-mesa-dev libglu-dev libgtk2.0-dev libguess-dev libjack-jackd2-dev liblircclient-dev libmms-dev libmodplug-dev libmp3lame-dev libmpg123-dev libneon27-gnutls-dev libnotify-dev libopenmpt-dev libpulse-dev libqt5opengl5-dev libqt5x11extras5-dev libsamplerate0-dev libsdl1.2-dev libsdl2-dev libsidplayfp-dev libsndfile1-dev libsoxr-dev libswscale-dev libvorbis-dev libvulkan-dev libwavpack-dev libxext-dev libxml2-dev qt5-qmake qtbase5-dev

(added)
2. Build the install path. Where Git retrieves all files needed to setup the latest version of Fauxdacious. The following series of commands will ensure this process will finish successfully. Copy them line by line below into the same terminal session.

(largely unchanged from the default accept for when referencing git, has to be https now otherwise git alone will time out when behind a firewall)
cd /tmp
mkdir fauxdacious
mkdir fauxdacious-plugins

git clone --single-branch https://github.com/wildstar84/fauxdacious.git fauxdacious
git clone --single-branch https://github.com/wildstar84/fauxdacious-plugins.git fauxdacious-plugins

(added)
3. Build the structure. You're half way there. As we did previously, copy the following lines to setup the source code into a working state.

(This section has some syntax complications that have been fixed)
cd fauxdacious
./autogen.sh
./configure --prefix=/usr/local --enable-qt --with-buildstamp=Fauxdacious
make
sudo make install
sudo ldconfig
cd ../fauxdacious-plugins
./autogen.sh
./configure --prefix=/usr/local --enable-qt
make
sudo make install
sudo update-desktop-database
sudo update-icon-caches /usr/share/icons/hicolor

(added)
4. For extra functionality, install the following Perl Scripts.
(advanced and incompatible steps follow from this point)
Make sure that:
File::Copy HTML::Entities HTML::Strip HTTP::Request LWP::UserAgent URI::Escape StreamFinder LyricFinder
...are installed as Perl Helper Modules.
Then run:
(errors out, unknown reason)
sudo cp fauxdacious/contrib/Fauxdacious*.pl /usr/local/bin/
sudo chmod 755 Fauxdacious*.pl

(added)
5. Finalize the installation. Convert your old Audacious settings into Fauxdacious. As before, copy this line into the terminal session.

(this part of the install also errors out...unsure if it is due to wrong paths or syntax)
cd ~/.config; mkdir fauxdacious; cp -R audacious/. fauxdacious

(added final note)
Enjoy.

Not sure if this could be more useful for you in gaining more users for this media player. But I myself see the huge potential of it and wanted to let you know of its many major improvements I have seen you be able to code directly into it.
Thank you sincerely.

**Comment by wildstar84** [comment]
Thank you for the kind words and (documenation) support (we programmers have a reputation of sucking at documentation)!  I am working on the README at the moment spurred on by the apparent travails of the creator of "Issue 9" and want to make this as accurate and painless for new users as possible.  Looking at your list and comparing it to my current one and Audacious's list (https://redmine.audacious-media-player.org/boards/1/topics/788), I discovered that libguess-dev isn't (any longer?) needed and doesn't currently exist (I'm using a distro based on latest Debian "Testing").  Fauxdacious, unlike Audacious requires libsdl2 (for video/DVD play) and does not require libsdl1.2.  I keep the Qt lib requiremens separate, since one can build the GTK version without them.  I'm assuming you're successfully using Fauxdacious though development has been very active as of late, so hope you've compiled the latest GIT commits and hope everything's working well for you.  Keep in mind though that unlike Audacious, this is just a one-man (me) operation and my programming background is in Perl (not C).  Be sure to read up on the FAQ for how to best take advantage of the difference between us and Audacious.

Regards,

Jim

**Comment by serrebi** [comment]
Likewise, Thanks for your patients with us.

**Comment by wildstar84** [comment]
I've made a few changes in the docs in the latest release (v4.2-final).  Closing due to lack of further response.
