### ISSUE TITLE
Problems with playing .m4a files in Fauxdacious (some plugin is malfunctioning?)

### ISSUE THREAD

**Issue by Sacolevas** [wildstar84/fauxdacious#12]
Hello Again, 

In the current version of Fauxdacious (I built from this repository with the instruction you gave me some time ago), there is an issue playing .m4a files. I don't know when the problem started (i.e I use to build approximately once a month, but I don't know in which version the problem appeared). 

I verified that the issue does not happen when I use audacious (also built from source), I guess it is a problem with some plugin.

Inside the .zip file I put a sample m4a file. 

[My Sweet Lord.zip](https://github.com/wildstar84/fauxdacious/files/10528677/My.Sweet.Lord.zip)

**Comment by wildstar84** [comment]
Hmmm - Plays for me using latest git (plus a few mnior albumart-related changes I haven't committed yet):  4:43' long with the following fmpeg warning:  "WARNING ffaudio-core.cc:355 [mov,mp4,m4a,3gp,3g2,mj2]: <0x7f1b2c2395c0> stream 0, timescale not set:  Can you better describe in more what's failing (refuses to play, garbled, cut off, crash, etc.), along with any error messages?  Are you running Windows or Linux? v4.2.1-final, or latest GIT as/of (date)?  What ffmpeg vsn. are you using?

Regards,

Jim

**Comment by wildstar84** [comment]
Closing due to lack of response.  Please reopen if ready to provide the information requested.

**Comment by Sacolevas** [comment]
Hello!!

My apologies,  this has been a very busy semester in college and it is not easy for me to answer in time. 

I sent a .zip file with two mp3 files; the way it sounds in audacious and the way it sounds in fauxdacious. 
---------------
ABOUT FFMPEG VERSION (It has worked before and have installed fauxdacious and audacious from source usinf your guide with the github version for over 18 months)

It says: ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-liblensfun --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100


---------------------

 NEW PROBLEM: Fauxdacious BuIld which has worjed all the time is not working for the first time in a while. 

These are the final lines, before the build process stops:

------

Configuration:

  Install path:                           /usr/local

  D-Bus support:                          yes
  GTK+ support:                           yes
  Qt support:                             yes
  SDL2 (Video) support:                   yes
  Valgrind analysis support:              yes

.... and then the final lines ....

Successfully compiled probe-buffer.cc (lib).
Successfully compiled ringbuf.cc (lib).
Successfully compiled runtime.cc (lib).
Successfully compiled scanner.cc (lib).
Successfully compiled stringbuf.cc (lib).
Successfully compiled strpool.cc (lib).
In file included from tinylock.cc:20:
tinylock.h:30:19: error: ambiguating new declaration of ‘void pthread_mutex_lock(TinyLock*)’
   30 | #define tiny_lock pthread_mutex_lock
      |                   ^~~~~~~~~~~~~~~~~~
tinylock.cc:27:13: note: in expansion of macro ‘tiny_lock’
   27 | EXPORT void tiny_lock (TinyLock * lock)
      |             ^~~~~~~~~
In file included from tinylock.h:25,
                 from tinylock.cc:20:
/usr/include/pthread.h:738:12: note: old declaration ‘int pthread_mutex_lock(pthread_mutex_t*)’
  738 | extern int pthread_mutex_lock (pthread_mutex_t *__mutex)
      |            ^~~~~~~~~~~~~~~~~~
tinylock.cc: In function ‘void pthread_mutex_lock(TinyLock*)’:
tinylock.cc:29:63: error: operand type ‘TinyLock*’ {aka ‘pthread_mutex_t*’} is incompatible with argument 1 of ‘__sync_lock_test_and_set’
   29 |     while (__builtin_expect (__sync_lock_test_and_set (lock, 1), 0))
      |                                                               ^
In file included from tinylock.cc:20:
tinylock.cc: At global scope:
tinylock.h:31:21: error: ambiguating new declaration of ‘void pthread_mutex_unlock(TinyLock*)’
   31 | #define tiny_unlock pthread_mutex_unlock
      |                     ^~~~~~~~~~~~~~~~~~~~
tinylock.cc:33:13: note: in expansion of macro ‘tiny_unlock’
   33 | EXPORT void tiny_unlock (TinyLock * lock)
      |             ^~~~~~~~~~~
In file included from tinylock.h:25,
                 from tinylock.cc:20:
/usr/include/pthread.h:756:12: note: old declaration ‘int pthread_mutex_unlock(pthread_mutex_t*)’
  756 | extern int pthread_mutex_unlock (pthread_mutex_t *__mutex)
      |            ^~~~~~~~~~~~~~~~~~~~
tinylock.cc: In function ‘void pthread_mutex_unlock(TinyLock*)’:
tinylock.cc:35:30: error: operand type ‘TinyLock*’ {aka ‘pthread_mutex_t*’} is incompatible with argument 1 of ‘__sync_lock_release’
   35 |     __sync_lock_release (lock);
      |                              ^
In file included from tinylock.cc:20:
tinylock.cc: At global scope:
tinylock.h:32:24: error: ambiguating new declaration of ‘void pthread_rwlock_rdlock(TinyRWLock*)’
   32 | #define tiny_lock_read pthread_rwlock_rdlock
      |                        ^~~~~~~~~~~~~~~~~~~~~
tinylock.cc:38:13: note: in expansion of macro ‘tiny_lock_read’
   38 | EXPORT void tiny_lock_read (TinyRWLock * lock)
      |             ^~~~~~~~~~~~~~
In file included from tinylock.h:25,
                 from tinylock.cc:20:
/usr/include/pthread.h:880:12: note: old declaration ‘int pthread_rwlock_rdlock(pthread_rwlock_t*)’
  880 | extern int pthread_rwlock_rdlock (pthread_rwlock_t *__rwlock)
      |            ^~~~~~~~~~~~~~~~~~~~~
tinylock.cc: In function ‘void pthread_rwlock_rdlock(TinyRWLock*)’:
tinylock.cc:40:59: error: operand type ‘TinyRWLock*’ {aka ‘pthread_rwlock_t*’} is incompatible with argument 1 of ‘__sync_fetch_and_add’
   40 |     while (__builtin_expect (__sync_fetch_and_add (lock, 1) & WRITE_BIT, 0))
      |                                                           ^
tinylock.cc:42:38: error: operand type ‘TinyRWLock*’ {aka ‘pthread_rwlock_t*’} is incompatible with argument 1 of ‘__sync_fetch_and_sub’
   42 |         __sync_fetch_and_sub (lock, 1);
      |                                      ^
In file included from tinylock.cc:20:
tinylock.cc: At global scope:
tinylock.h:33:26: error: ambiguating new declaration of ‘void pthread_rwlock_unlock(TinyRWLock*)’
   33 | #define tiny_unlock_read pthread_rwlock_unlock
      |                          ^~~~~~~~~~~~~~~~~~~~~
tinylock.cc:47:13: note: in expansion of macro ‘tiny_unlock_read’
   47 | EXPORT void tiny_unlock_read (TinyRWLock * lock)
      |             ^~~~~~~~~~~~~~~~
In file included from tinylock.h:25,
                 from tinylock.cc:20:
/usr/include/pthread.h:924:12: note: old declaration ‘int pthread_rwlock_unlock(pthread_rwlock_t*)’
  924 | extern int pthread_rwlock_unlock (pthread_rwlock_t *__rwlock)
      |            ^~~~~~~~~~~~~~~~~~~~~
tinylock.cc: In function ‘void pthread_rwlock_unlock(TinyRWLock*)’:
tinylock.cc:49:34: error: operand type ‘TinyRWLock*’ {aka ‘pthread_rwlock_t*’} is incompatible with argument 1 of ‘__sync_fetch_and_sub’
   49 |     __sync_fetch_and_sub (lock, 1);
      |                                  ^
In file included from tinylock.cc:20:
tinylock.cc: At global scope:
tinylock.h:34:25: error: ambiguating new declaration of ‘void pthread_rwlock_wrlock(TinyRWLock*)’
   34 | #define tiny_lock_write pthread_rwlock_wrlock
      |                         ^~~~~~~~~~~~~~~~~~~~~
tinylock.cc:52:13: note: in expansion of macro ‘tiny_lock_write’
   52 | EXPORT void tiny_lock_write (TinyRWLock * lock)
      |             ^~~~~~~~~~~~~~~
In file included from tinylock.h:25,
                 from tinylock.cc:20:
/usr/include/pthread.h:902:12: note: old declaration ‘int pthread_rwlock_wrlock(pthread_rwlock_t*)’
  902 | extern int pthread_rwlock_wrlock (pthread_rwlock_t *__rwlock)
      |            ^~~~~~~~~~~~~~~~~~~~~
tinylock.cc: In function ‘void pthread_rwlock_wrlock(TinyRWLock*)’:
tinylock.cc:54:80: error: operand type ‘TinyRWLock*’ {aka ‘pthread_rwlock_t*’} is incompatible with argument 1 of ‘__sync_bool_compare_and_swap’
   54 | ltin_expect (__sync_bool_compare_and_swap (lock, 0, WRITE_BIT), 1))
      |                                                              ^

In file included from tinylock.cc:20:
tinylock.cc: At global scope:
tinylock.h:35:27: error: ambiguating new declaration of ‘void pthread_rwlock_unlock(TinyRWLock*)’
   35 | #define tiny_unlock_write pthread_rwlock_unlock
      |                           ^~~~~~~~~~~~~~~~~~~~~
tinylock.cc:58:13: note: in expansion of macro ‘tiny_unlock_write’
   58 | EXPORT void tiny_unlock_write (TinyRWLock * lock)
      |             ^~~~~~~~~~~~~~~~~
In file included from tinylock.h:25,
                 from tinylock.cc:20:
/usr/include/pthread.h:924:12: note: old declaration ‘int pthread_rwlock_unlock(pthread_rwlock_t*)’
  924 | extern int pthread_rwlock_unlock (pthread_rwlock_t *__rwlock)
      |            ^~~~~~~~~~~~~~~~~~~~~
tinylock.cc: In function ‘void pthread_rwlock_unlock(TinyRWLock*)’:
tinylock.cc:60:42: error: operand type ‘TinyRWLock*’ {aka ‘pthread_rwlock_t*’} is incompatible with argument 1 of ‘__sync_fetch_and_sub’
   60 |     __sync_fetch_and_sub (lock, WRITE_BIT);
      |                                          ^
Failed to compile tinylock.cc (lib)!
make[5]: *** [../../buildsys.mk:418: tinylock.lib.o] Error 1
make[4]: *** [../../buildsys.mk:134: all] Error 2
make[3]: *** [../buildsys.mk:144: libfauxdcore] Error 2
make[2]: *** [../buildsys.mk:132: all] Error 2
make[1]: *** [buildsys.mk:144: src] Error 2
make: *** [buildsys.mk:132: all] Error 2
------------------

Thanks for your attention, I hope I have given you enough information to solve these two problems


[Recordings.zip](https://github.com/wildstar84/fauxdacious/files/10974618/Recordings.zip)
