### ISSUE TITLE
Feature request: press space to play/pause

### ISSUE THREAD

**Issue by rexendevar** [wildstar84/fauxdacious#17]
Much as I may not want to, I miss Spotify because it let me play and pause by pressing the spacebar when the window was focused. The way my computer is set up, I have to either use the mouse (ew) or press a tiny little play pause key up at the top of the keyboard.

**Comment by wildstar84** [comment]
I agree & added this feature a long time ago.  When either the Fauxdacious main window or the Mini-Fauxdacious plugin window has keyboard focus, this works for me.  How do you "have your computer set up?" and what interface are you using (GTK/Qt, skins or main)?

**Comment by rexendevar** [comment]
I am stupid and did not focus the window properly. The cursor was going into the lyrics pane and typing spaces at the end of lines.
