### ISSUE TITLE
Fauxdacious Icon not Working (Status Icon) once you compile and install Fauxdacious|

### ISSUE THREAD

**Issue by Sacolevas** [wildstar84/fauxdacious#4]
Hi again!!!!

First at all, I hope everything is ok for you! Two questions:

1) Small: Could you update the LyricsWiki extension adding sites like the one suggested? I hope if that is possible.
2) Important, but easy to solve, I think: I compiled fauxdacious using the latest github version, and the application icon in desktop shorcut and status icon in the taskbar don't appear. Digging a little further, the cause lies in the fauxdacious.svg file, in location /usr/local/share/icons/hicolor/scalable/apps/.

This is the message when I tried to open the file.
![image](https://user-images.githubusercontent.com/1384450/106994436-c1b46d00-674a-11eb-99bf-d850dd1eb11a.png)
(So it looks like the file is broken!)

When compiling Audacious, if appears file audacious.svg in the same folder, which open normally. 

In consequence, at the moment, just copying audacious.svg icon in the same folder, and renaming it to fauxdacious.svg solves the problem (of course, in status icon and desktop shortcut I see audacious icon instead of fauxdacious, but at least an icon appear!). But of course, it is not the ideal solution, because fauxdacious logo is very important for the recognition and identity of the program!

Thanks for your attention!

**Comment by wildstar84** [comment]
Look for /usr/local/share/icons/hicolor/24x24/apps/fauxdacious.png and /usr/local/share/icons/hicolor/48x48/apps/fauxdacious.png (Fauxdacious commits# 16ad80a and 31419a1).  This is a known issue/workaround for fauxdacious.svg.  The pbm. is that unlike John Lindgren, et. al. I do not know how or have software that will create an svg image that will work in all situations (I tried GIMP, which converted the png to "svg", but apparently not quite in the format that GTK likes)  , so I use .pngs for the fauxdacious-specific icons I had to create.  NOTE, I had issues getting the new icons to register and show up too, so you may have to re-check out the latest 4.1.1-final GIT (with these commits and others) and completely rebuild to get it to "take" - particularly on the GTK side (autogen.sh, configure, make, etc.), sorry.

Regards,

Jim

**Comment by wildstar84** [comment]
I'm currently not particularly keen on adding new lyrics sites right now, as having more sites to search slows down lyric searches.  I experimented w/a cpl of sites (Letras - the one you requested, and ELyrics), but they didn't seem to find hardly any more songs than were already available on the current sites.  I did make a change to the MusixMatch plugin to handle the UTF-8 Spanish chars and so the song you mentioned should work now (v1.01).  The Russian one I could not get to work as the chars are very different and being an English-only guy myself, I have very little knowledge a/b mapping, handling, and converting char-sets.  If you can suggest a lyrics site that actually contains a variety of songs markedly different from what's offered now and isn't contry/language-specific, perhaps I'll consider it.

**Comment by wildstar84** [comment]
If you really want Letras or ELyrics, drop me a direct email and I'll send you the code I did to test these sites attached to the reply, and you can add them to LyricFinder yourself for your own use.

**Comment by wildstar84** [comment]
Closing assuming these issues are resolved satisfactorily due to lack of further response.
