### ISSUE TITLE
Request: Option to Change System Language in Fauxdacious GUI

### ISSUE THREAD

**Issue by Sacolevas** [wildstar84/fauxdacious#5]
Hi Again! I don't know if there is a change of adding this option in fauxdacious!

For example, I have the Windows version and the computer has two users; one trying to use Audacious in Spanish (system default), but I prefer in English. The only way to put in English for me was to delete all directory names from other languages, but then the other person is forced to use English as system language. And if I don't delete language directories, I am forced to use Spanish which I don't like in the interface!

Thanks in advance, have a good day!

**Comment by wildstar84** [comment]
See Audacious feature request for how to do this:  https://redmine.audacious-media-player.org/issues/1058
Be forwarned though, that I haven't kept up the transiflex translations (particularly for all the Fauxdacious-specific menus, etc. (labor, laziness, lack of demand/time/etc.), so the translations in Fauxdacious will pbly be spotty!  Perhaps you be willing to contribute (time) to help with this?

Jim

**Comment by wildstar84** [comment]
Closing due to lack of further responses.
